// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKCL9Gl-4BiT1MCbs0Y1TClzVl3E5vDR4',
    appId: '1:169731905594:web:9246b64052b89acf677d03',
    messagingSenderId: '169731905594',
    projectId: 'urla-balikliova',
    authDomain: 'urla-balikliova.firebaseapp.com',
    databaseURL: 'https://urla-balikliova-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'urla-balikliova.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhUUVJnJIYXfyJAxX_sIMlx2Nep9U3bXU',
    appId: '1:169731905594:android:c4366575aa1487c3677d03',
    messagingSenderId: '169731905594',
    projectId: 'urla-balikliova',
    databaseURL: 'https://urla-balikliova-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'urla-balikliova.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6-qAnoBh_A3GtDoZueW_gXP91YQibWNM',
    appId: '1:169731905594:ios:40b26a1f2c4413ca677d03',
    messagingSenderId: '169731905594',
    projectId: 'urla-balikliova',
    databaseURL: 'https://urla-balikliova-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'urla-balikliova.appspot.com',
    iosClientId: '169731905594-01885bc8qdmj6d8fvnj0vi4fqnsehua0.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
